# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Anthony K GROSS
baseurl: ""
url: "http://localhost"
lang: fr-FR
env: dev

project_url: https://github.com/anthonykgross/anthonykgross.github.io

socials:
  twitter:
    username: AnthonyKGROSS
    url: https://twitter.com/anthonykgross
    fontawesome: fa fa-twitter
  youtube:
    username: AnthonyKGROSS
    url: https://www.youtube.com/channel/UC7hF0LUlIoShX2QZejF7z7g
    fontawesome: fa fa-youtube-play
  linkedin:
    username: anthony-k-gross
    url: https://www.linkedin.com/pub/anthony-k-gross/6a/863/16
    fontawesome: fa fa-linkedin
  github:
    username: AnthonyKGROSS
    url: https://github.com/anthonykgross
    fontawesome: fa fa-github
  docker_hub:
    username: AnthonyKGROSS
    url: https://hub.docker.com/u/anthonykgross/
    fontawesome: fa fa-cubes
  rss:
    username: AnthonyKGROSS
    url: /feed.xml
    fontawesome: fa fa-rss

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-postcss

# other configs
exclude:
  - CNAME
  - README.md
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - Makefile
  - yarn.lock
  - gulpfile.js
  - .idea