on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v2
      - name: Config for Production
        run: | 
          mv -f _config_prod.yml _config.yml
          sed -i -e "s,__GH_TOKEN__,${{ secrets.GH_TOKEN }},g" _config.yml

      - name: Install Dependencies
        run: npm install -g gulp && yarn && gulp

      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          jekyll/builder:latest bash -c "chmod -R 777 /srv/jekyll && jekyll build"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
